package im.vector.app.kelare.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import im.vector.app.kelare.network.models.PeopleRoom;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PEOPLE_ROOM".
*/
public class PeopleRoomDao extends AbstractDao<PeopleRoom, Void> {

    public static final String TABLENAME = "PEOPLE_ROOM";

    /**
     * Properties of entity PeopleRoom.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property People_room_id = new Property(0, String.class, "people_room_id", false, "PEOPLE_ROOM_ID");
        public final static Property Login_account_jid = new Property(1, String.class, "login_account_jid", false, "LOGIN_ACCOUNT_JID");
        public final static Property Login_name = new Property(2, String.class, "login_name", false, "LOGIN_NAME");
        public final static Property Login_account = new Property(3, String.class, "login_account", false, "LOGIN_ACCOUNT");
        public final static Property Chat_with_jid = new Property(4, String.class, "chat_with_jid", false, "CHAT_WITH_JID");
        public final static Property Latest_message = new Property(5, String.class, "latest_message", false, "LATEST_MESSAGE");
    }


    public PeopleRoomDao(DaoConfig config) {
        super(config);
    }
    
    public PeopleRoomDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PEOPLE_ROOM\" (" + //
                "\"PEOPLE_ROOM_ID\" TEXT," + // 0: people_room_id
                "\"LOGIN_ACCOUNT_JID\" TEXT," + // 1: login_account_jid
                "\"LOGIN_NAME\" TEXT," + // 2: login_name
                "\"LOGIN_ACCOUNT\" TEXT," + // 3: login_account
                "\"CHAT_WITH_JID\" TEXT," + // 4: chat_with_jid
                "\"LATEST_MESSAGE\" TEXT);"); // 5: latest_message
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PEOPLE_ROOM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PeopleRoom entity) {
        stmt.clearBindings();
 
        String people_room_id = entity.getPeople_room_id();
        if (people_room_id != null) {
            stmt.bindString(1, people_room_id);
        }
 
        String login_account_jid = entity.getLogin_account_jid();
        if (login_account_jid != null) {
            stmt.bindString(2, login_account_jid);
        }
 
        String login_name = entity.getLogin_name();
        if (login_name != null) {
            stmt.bindString(3, login_name);
        }
 
        String login_account = entity.getLogin_account();
        if (login_account != null) {
            stmt.bindString(4, login_account);
        }
 
        String chat_with_jid = entity.getChat_with_jid();
        if (chat_with_jid != null) {
            stmt.bindString(5, chat_with_jid);
        }
 
        String latest_message = entity.getLatest_message();
        if (latest_message != null) {
            stmt.bindString(6, latest_message);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PeopleRoom entity) {
        stmt.clearBindings();
 
        String people_room_id = entity.getPeople_room_id();
        if (people_room_id != null) {
            stmt.bindString(1, people_room_id);
        }
 
        String login_account_jid = entity.getLogin_account_jid();
        if (login_account_jid != null) {
            stmt.bindString(2, login_account_jid);
        }
 
        String login_name = entity.getLogin_name();
        if (login_name != null) {
            stmt.bindString(3, login_name);
        }
 
        String login_account = entity.getLogin_account();
        if (login_account != null) {
            stmt.bindString(4, login_account);
        }
 
        String chat_with_jid = entity.getChat_with_jid();
        if (chat_with_jid != null) {
            stmt.bindString(5, chat_with_jid);
        }
 
        String latest_message = entity.getLatest_message();
        if (latest_message != null) {
            stmt.bindString(6, latest_message);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public PeopleRoom readEntity(Cursor cursor, int offset) {
        PeopleRoom entity = new PeopleRoom( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // people_room_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // login_account_jid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // login_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // login_account
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // chat_with_jid
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // latest_message
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PeopleRoom entity, int offset) {
        entity.setPeople_room_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setLogin_account_jid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLogin_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLogin_account(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setChat_with_jid(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLatest_message(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(PeopleRoom entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(PeopleRoom entity) {
        return null;
    }

    @Override
    public boolean hasKey(PeopleRoom entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
